apiVersion: v1
kind: ConfigMap
metadata: 
  name: colin-scraper-config
data:
  STAFF_USERNAME: 
  STAFF_PASSWORD:  
  ORACLE_DB_USERNAME: 
  ORACLE_DB_PASSWORD: 
  ORACLE_DB_DSN: 
  DATE_RANGE_START: 
  DATE_RANGE_END: 
  FINAL_END_DATE: 
